version: "3.0"

services:
    logstash:
        image: docker.elastic.co/logstash/logstash:7.12.1
        container_name: logstash_heartbeat
        ports:
            - 5044:5044
        volumes:
            - ./pipelines/pipeline_heartbeat.conf:/usr/share/logstash/pipeline/logstash.conf
            - /home/ubuntu/environment/datos/certs/ca:/etc/logstash/certs/ca
    logstash:
        image: docker.elastic.co/logstash/logstash:7.12.1
        container_name: logstash_metricbeat
        ports:
            - 5045:5044
        volumes:
            - ./pipelines/pipeline_metricbeat.conf:/usr/share/logstash/pipeline/logstash.conf
            - /home/ubuntu/environment/datos/certs/ca:/etc/logstash/certs/ca
    logstash:
        image: docker.elastic.co/logstash/logstash:7.12.1
        container_name: logstash_filebeat
        ports:
            - 5046:5044
        volumes:
            - ./pipelines/pipeline_filebeat.conf:/usr/share/logstash/pipeline/logstash.conf
            - /home/ubuntu/environment/datos/certs/ca:/etc/logstash/certs/ca
