#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true

#processors:
#- add_cloud_metadata: ~

filebeat.inputs:
  - type: log
    paths:
      - /tmp/access_log

output.elasticsearch:
  hosts: ['172.31.11.249:8080']
