docker run --rm \
docker.elastic.co/beats/filebeat:7.12.0 \
setup -E setup.kibana.host=172.31.11.249:8082 \
-E output.elasticsearch.hosts=["172.31.11.249:8080"]



docker run  \
  --name=filebeat \
  --user=root \
  --volume="$(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro" \
  --volume="/home/ubuntu/environment/datos/access_log:/tmp/access_log" \
  --volume="/var/lib/docker/containers:/var/lib/docker/containers:ro" \
  --volume="/var/run/docker.sock:/var/run/docker.sock:ro" \
  docker.elastic.co/beats/filebeat:7.12.0 filebeat -e -strict.perms=false \
  -E output.elasticsearch.hosts=["172.31.11.249:8080"]  
  
  
  docker run \
    --name=filebeat \
    --rm \
    -v "/home/ubuntu/environment/curso/instalacion/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml" \
    -v "/home/ubuntu/environment/datos/access_log:/tmp/access_log" \
    docker.elastic.co/beats/filebeat:7.12.0