heartbeat.monitors:
- type: http
  id: mi-apache
  name: mi-apache
  schedule: '@every 5s'
  hosts:
    - http://172.31.11.249:8080
  check.response.status: [200]

output.logstash:
  hosts: ['172.31.11.249:5044']