version: "3.0"

services:
    mi-apache:
        image: httpd
        container_name: mi-apache
        ports:
            - 8080:80
        volumes:
            # Garantizar que se trabaje con nuestro fichero de conf
            #  en el cual hemos activado el fichero de log:
            # /usr/local/apache2/logs/access_log
            - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
            # Exporto el archivo de log al host
            - /home/ubuntu/environment/datos/access_log:/usr/local/apache2/logs/access_log

    heartbeat:
        image: docker.elastic.co/beats/heartbeat:7.12.1
        container_name: mi-apache-heartbeat
        volumes:
            - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro

    heartbeat-setup:
        image: docker.elastic.co/beats/heartbeat:7.12.1
        container_name: mi-apache-heartbeat-setup
        command: [ 'sh' , '-c' , >
            'heartbeat setup -E setup.kibana.username=elastic '
            '-E setup.kibana.password=password '
            '-E output.elasticsearch.ssl.certificate_authorities=["/etc/logstash/certs/ca/ca.crt"] '
            '-E setup.kibana.host=https://172.31.11.249:8082 '
            '-E output.elasticsearch.username=elastic '
            '-E output.elasticsearch.password=password '
            '-E output.elasticsearch.hosts=["https://172.31.11.249:9200"]' 
           ]
        volumes:
            - /home/ubuntu/environment/datos/certs/ca:/etc/logstash/certs/ca
